name: "My First GitHub Actions"

on: push

jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest

    steps:
      - name: Set output value 1
        id: first
        shell: bash
        run: |
          value1='This is the first value'

          echo "::set-output name=first_value::$value1"

      - name: Set output value 2
        id: second
        shell: pwsh
        run: |
          $value2 = "This is the second value"

          echo "::set-output name=second_value::$value2"

      - name: Check output vlaue
        shell: bash
        run: |
          echo "first value: ${{ steps.first.outputs.first_value }}"
          echo "second value: ${{ steps.first.outputs.second_value }}"
