name: "My First GitHub Actions"

on: push

env:
  PRESET_VALUE: "This is the value preset"

jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable 1
        shell: bash
        run: |
          echo "VAR1='This is the value from the step 1'" >> $GITHUB_ENV
      - name: Set environment variable 2
        shell: pwsh
        run: |
          echo "VAR2='This is the value from the step 2'" | `
            Out-File -FilePath $env:GITHUB_ENV -Encoding UTF-8 -Append
      - name: Check environment variables
        shell: bash
        run: |
          echo "preset value: ${{ env.PRESET_VALUE }}"
          echo "var1: $VAR1"
          echo "var2: $VAR2"
