name: "My First GitHub Actions"

on: push

jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello World 1"
        shell: bash
        run: |
          echo "Hello World from Step #1"
      - name: "Say Lorem Ipsum 2"
        shell: pwsh
        run: |
          echo "Lorem Ipsum from Step #2"
